// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AllConfig.proto

#ifndef PROTOBUF_INCLUDED_AllConfig_2eproto
#define PROTOBUF_INCLUDED_AllConfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_AllConfig_2eproto 

namespace protobuf_AllConfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[10];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_AllConfig_2eproto
namespace proto {
class AllConfig;
class AllConfigDefaultTypeInternal;
extern AllConfigDefaultTypeInternal _AllConfig_default_instance_;
class AlternateRouting;
class AlternateRoutingDefaultTypeInternal;
extern AlternateRoutingDefaultTypeInternal _AlternateRouting_default_instance_;
class Cell;
class CellDefaultTypeInternal;
extern CellDefaultTypeInternal _Cell_default_instance_;
class Filepaths;
class FilepathsDefaultTypeInternal;
extern FilepathsDefaultTypeInternal _Filepaths_default_instance_;
class GraphicRendering;
class GraphicRenderingDefaultTypeInternal;
extern GraphicRenderingDefaultTypeInternal _GraphicRendering_default_instance_;
class PenStroke;
class PenStrokeDefaultTypeInternal;
extern PenStrokeDefaultTypeInternal _PenStroke_default_instance_;
class Placement;
class PlacementDefaultTypeInternal;
extern PlacementDefaultTypeInternal _Placement_default_instance_;
class Routing;
class RoutingDefaultTypeInternal;
extern RoutingDefaultTypeInternal _Routing_default_instance_;
class RoutingCost;
class RoutingCostDefaultTypeInternal;
extern RoutingCostDefaultTypeInternal _RoutingCost_default_instance_;
class SkeletonGrid;
class SkeletonGridDefaultTypeInternal;
extern SkeletonGridDefaultTypeInternal _SkeletonGrid_default_instance_;
}  // namespace proto
namespace google {
namespace protobuf {
template<> ::proto::AllConfig* Arena::CreateMaybeMessage<::proto::AllConfig>(Arena*);
template<> ::proto::AlternateRouting* Arena::CreateMaybeMessage<::proto::AlternateRouting>(Arena*);
template<> ::proto::Cell* Arena::CreateMaybeMessage<::proto::Cell>(Arena*);
template<> ::proto::Filepaths* Arena::CreateMaybeMessage<::proto::Filepaths>(Arena*);
template<> ::proto::GraphicRendering* Arena::CreateMaybeMessage<::proto::GraphicRendering>(Arena*);
template<> ::proto::PenStroke* Arena::CreateMaybeMessage<::proto::PenStroke>(Arena*);
template<> ::proto::Placement* Arena::CreateMaybeMessage<::proto::Placement>(Arena*);
template<> ::proto::Routing* Arena::CreateMaybeMessage<::proto::Routing>(Arena*);
template<> ::proto::RoutingCost* Arena::CreateMaybeMessage<::proto::RoutingCost>(Arena*);
template<> ::proto::SkeletonGrid* Arena::CreateMaybeMessage<::proto::SkeletonGrid>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace proto {

// ===================================================================

class Filepaths : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.Filepaths) */ {
 public:
  Filepaths();
  virtual ~Filepaths();

  Filepaths(const Filepaths& from);

  inline Filepaths& operator=(const Filepaths& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Filepaths(Filepaths&& from) noexcept
    : Filepaths() {
    *this = ::std::move(from);
  }

  inline Filepaths& operator=(Filepaths&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Filepaths& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Filepaths* internal_default_instance() {
    return reinterpret_cast<const Filepaths*>(
               &_Filepaths_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Filepaths* other);
  friend void swap(Filepaths& a, Filepaths& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Filepaths* New() const final {
    return CreateMaybeMessage<Filepaths>(NULL);
  }

  Filepaths* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Filepaths>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Filepaths& from);
  void MergeFrom(const Filepaths& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Filepaths* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string outputfile = 1;
  void clear_outputfile();
  static const int kOutputfileFieldNumber = 1;
  const ::std::string& outputfile() const;
  void set_outputfile(const ::std::string& value);
  #if LANG_CXX11
  void set_outputfile(::std::string&& value);
  #endif
  void set_outputfile(const char* value);
  void set_outputfile(const char* value, size_t size);
  ::std::string* mutable_outputfile();
  ::std::string* release_outputfile();
  void set_allocated_outputfile(::std::string* outputfile);

  // string inputfile = 2;
  void clear_inputfile();
  static const int kInputfileFieldNumber = 2;
  const ::std::string& inputfile() const;
  void set_inputfile(const ::std::string& value);
  #if LANG_CXX11
  void set_inputfile(::std::string&& value);
  #endif
  void set_inputfile(const char* value);
  void set_inputfile(const char* value, size_t size);
  ::std::string* mutable_inputfile();
  ::std::string* release_inputfile();
  void set_allocated_inputfile(::std::string* inputfile);

  // @@protoc_insertion_point(class_scope:proto.Filepaths)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr outputfile_;
  ::google::protobuf::internal::ArenaStringPtr inputfile_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AllConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PenStroke : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.PenStroke) */ {
 public:
  PenStroke();
  virtual ~PenStroke();

  PenStroke(const PenStroke& from);

  inline PenStroke& operator=(const PenStroke& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PenStroke(PenStroke&& from) noexcept
    : PenStroke() {
    *this = ::std::move(from);
  }

  inline PenStroke& operator=(PenStroke&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PenStroke& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PenStroke* internal_default_instance() {
    return reinterpret_cast<const PenStroke*>(
               &_PenStroke_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(PenStroke* other);
  friend void swap(PenStroke& a, PenStroke& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PenStroke* New() const final {
    return CreateMaybeMessage<PenStroke>(NULL);
  }

  PenStroke* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PenStroke>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PenStroke& from);
  void MergeFrom(const PenStroke& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PenStroke* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double thickness = 1;
  void clear_thickness();
  static const int kThicknessFieldNumber = 1;
  double thickness() const;
  void set_thickness(double value);

  // double antisymmetric_amplitude = 2;
  void clear_antisymmetric_amplitude();
  static const int kAntisymmetricAmplitudeFieldNumber = 2;
  double antisymmetric_amplitude() const;
  void set_antisymmetric_amplitude(double value);

  // double antisymmetric_freq = 3;
  void clear_antisymmetric_freq();
  static const int kAntisymmetricFreqFieldNumber = 3;
  double antisymmetric_freq() const;
  void set_antisymmetric_freq(double value);

  // double antisymmetric_seed = 4;
  void clear_antisymmetric_seed();
  static const int kAntisymmetricSeedFieldNumber = 4;
  double antisymmetric_seed() const;
  void set_antisymmetric_seed(double value);

  // double symmetric_amplitude = 5;
  void clear_symmetric_amplitude();
  static const int kSymmetricAmplitudeFieldNumber = 5;
  double symmetric_amplitude() const;
  void set_symmetric_amplitude(double value);

  // double symmetric_freq = 6;
  void clear_symmetric_freq();
  static const int kSymmetricFreqFieldNumber = 6;
  double symmetric_freq() const;
  void set_symmetric_freq(double value);

  // double symmetric_seed = 7;
  void clear_symmetric_seed();
  static const int kSymmetricSeedFieldNumber = 7;
  double symmetric_seed() const;
  void set_symmetric_seed(double value);

  // double resolution = 8;
  void clear_resolution();
  static const int kResolutionFieldNumber = 8;
  double resolution() const;
  void set_resolution(double value);

  // @@protoc_insertion_point(class_scope:proto.PenStroke)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double thickness_;
  double antisymmetric_amplitude_;
  double antisymmetric_freq_;
  double antisymmetric_seed_;
  double symmetric_amplitude_;
  double symmetric_freq_;
  double symmetric_seed_;
  double resolution_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AllConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GraphicRendering : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GraphicRendering) */ {
 public:
  GraphicRendering();
  virtual ~GraphicRendering();

  GraphicRendering(const GraphicRendering& from);

  inline GraphicRendering& operator=(const GraphicRendering& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GraphicRendering(GraphicRendering&& from) noexcept
    : GraphicRendering() {
    *this = ::std::move(from);
  }

  inline GraphicRendering& operator=(GraphicRendering&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GraphicRendering& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GraphicRendering* internal_default_instance() {
    return reinterpret_cast<const GraphicRendering*>(
               &_GraphicRendering_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(GraphicRendering* other);
  friend void swap(GraphicRendering& a, GraphicRendering& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GraphicRendering* New() const final {
    return CreateMaybeMessage<GraphicRendering>(NULL);
  }

  GraphicRendering* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GraphicRendering>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GraphicRendering& from);
  void MergeFrom(const GraphicRendering& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GraphicRendering* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string outputfile = 1;
  void clear_outputfile();
  static const int kOutputfileFieldNumber = 1;
  const ::std::string& outputfile() const;
  void set_outputfile(const ::std::string& value);
  #if LANG_CXX11
  void set_outputfile(::std::string&& value);
  #endif
  void set_outputfile(const char* value);
  void set_outputfile(const char* value, size_t size);
  ::std::string* mutable_outputfile();
  ::std::string* release_outputfile();
  void set_allocated_outputfile(::std::string* outputfile);

  // string inputfile = 2;
  void clear_inputfile();
  static const int kInputfileFieldNumber = 2;
  const ::std::string& inputfile() const;
  void set_inputfile(const ::std::string& value);
  #if LANG_CXX11
  void set_inputfile(::std::string&& value);
  #endif
  void set_inputfile(const char* value);
  void set_inputfile(const char* value, size_t size);
  ::std::string* mutable_inputfile();
  ::std::string* release_inputfile();
  void set_allocated_inputfile(::std::string* inputfile);

  // .proto.PenStroke penConfig = 9;
  bool has_penconfig() const;
  void clear_penconfig();
  static const int kPenConfigFieldNumber = 9;
  private:
  const ::proto::PenStroke& _internal_penconfig() const;
  public:
  const ::proto::PenStroke& penconfig() const;
  ::proto::PenStroke* release_penconfig();
  ::proto::PenStroke* mutable_penconfig();
  void set_allocated_penconfig(::proto::PenStroke* penconfig);

  // double smoothing_tension = 3;
  void clear_smoothing_tension();
  static const int kSmoothingTensionFieldNumber = 3;
  double smoothing_tension() const;
  void set_smoothing_tension(double value);

  // double smoothing_iterations = 4;
  void clear_smoothing_iterations();
  static const int kSmoothingIterationsFieldNumber = 4;
  double smoothing_iterations() const;
  void set_smoothing_iterations(double value);

  // @@protoc_insertion_point(class_scope:proto.GraphicRendering)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr outputfile_;
  ::google::protobuf::internal::ArenaStringPtr inputfile_;
  ::proto::PenStroke* penconfig_;
  double smoothing_tension_;
  double smoothing_iterations_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AllConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SkeletonGrid : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.SkeletonGrid) */ {
 public:
  SkeletonGrid();
  virtual ~SkeletonGrid();

  SkeletonGrid(const SkeletonGrid& from);

  inline SkeletonGrid& operator=(const SkeletonGrid& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SkeletonGrid(SkeletonGrid&& from) noexcept
    : SkeletonGrid() {
    *this = ::std::move(from);
  }

  inline SkeletonGrid& operator=(SkeletonGrid&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SkeletonGrid& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SkeletonGrid* internal_default_instance() {
    return reinterpret_cast<const SkeletonGrid*>(
               &_SkeletonGrid_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(SkeletonGrid* other);
  friend void swap(SkeletonGrid& a, SkeletonGrid& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SkeletonGrid* New() const final {
    return CreateMaybeMessage<SkeletonGrid>(NULL);
  }

  SkeletonGrid* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SkeletonGrid>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SkeletonGrid& from);
  void MergeFrom(const SkeletonGrid& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SkeletonGrid* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string outputfile = 1;
  void clear_outputfile();
  static const int kOutputfileFieldNumber = 1;
  const ::std::string& outputfile() const;
  void set_outputfile(const ::std::string& value);
  #if LANG_CXX11
  void set_outputfile(::std::string&& value);
  #endif
  void set_outputfile(const char* value);
  void set_outputfile(const char* value, size_t size);
  ::std::string* mutable_outputfile();
  ::std::string* release_outputfile();
  void set_allocated_outputfile(::std::string* outputfile);

  // string inputfile = 2;
  void clear_inputfile();
  static const int kInputfileFieldNumber = 2;
  const ::std::string& inputfile() const;
  void set_inputfile(const ::std::string& value);
  #if LANG_CXX11
  void set_inputfile(::std::string&& value);
  #endif
  void set_inputfile(const char* value);
  void set_inputfile(const char* value, size_t size);
  ::std::string* mutable_inputfile();
  ::std::string* release_inputfile();
  void set_allocated_inputfile(::std::string* inputfile);

  // double simplificationOfOriginalSVG = 3;
  void clear_simplificationoforiginalsvg();
  static const int kSimplificationOfOriginalSVGFieldNumber = 3;
  double simplificationoforiginalsvg() const;
  void set_simplificationoforiginalsvg(double value);

  // double max_sep = 4;
  void clear_max_sep();
  static const int kMaxSepFieldNumber = 4;
  double max_sep() const;
  void set_max_sep(double value);

  // double min_sep = 5;
  void clear_min_sep();
  static const int kMinSepFieldNumber = 5;
  double min_sep() const;
  void set_min_sep(double value);

  // uint32 seed = 6;
  void clear_seed();
  static const int kSeedFieldNumber = 6;
  ::google::protobuf::uint32 seed() const;
  void set_seed(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.SkeletonGrid)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr outputfile_;
  ::google::protobuf::internal::ArenaStringPtr inputfile_;
  double simplificationoforiginalsvg_;
  double max_sep_;
  double min_sep_;
  ::google::protobuf::uint32 seed_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AllConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RoutingCost : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.RoutingCost) */ {
 public:
  RoutingCost();
  virtual ~RoutingCost();

  RoutingCost(const RoutingCost& from);

  inline RoutingCost& operator=(const RoutingCost& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoutingCost(RoutingCost&& from) noexcept
    : RoutingCost() {
    *this = ::std::move(from);
  }

  inline RoutingCost& operator=(RoutingCost&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RoutingCost& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoutingCost* internal_default_instance() {
    return reinterpret_cast<const RoutingCost*>(
               &_RoutingCost_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(RoutingCost* other);
  friend void swap(RoutingCost& a, RoutingCost& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoutingCost* New() const final {
    return CreateMaybeMessage<RoutingCost>(NULL);
  }

  RoutingCost* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RoutingCost>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RoutingCost& from);
  void MergeFrom(const RoutingCost& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoutingCost* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 seed = 1;
  void clear_seed();
  static const int kSeedFieldNumber = 1;
  ::google::protobuf::uint32 seed() const;
  void set_seed(::google::protobuf::uint32 value);

  // int32 max_random = 2;
  void clear_max_random();
  static const int kMaxRandomFieldNumber = 2;
  ::google::protobuf::int32 max_random() const;
  void set_max_random(::google::protobuf::int32 value);

  // int32 distance_unit_cost = 3;
  void clear_distance_unit_cost();
  static const int kDistanceUnitCostFieldNumber = 3;
  ::google::protobuf::int32 distance_unit_cost() const;
  void set_distance_unit_cost(::google::protobuf::int32 value);

  // int32 via_unit_cost = 4;
  void clear_via_unit_cost();
  static const int kViaUnitCostFieldNumber = 4;
  ::google::protobuf::int32 via_unit_cost() const;
  void set_via_unit_cost(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.RoutingCost)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 seed_;
  ::google::protobuf::int32 max_random_;
  ::google::protobuf::int32 distance_unit_cost_;
  ::google::protobuf::int32 via_unit_cost_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AllConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Cell : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.Cell) */ {
 public:
  Cell();
  virtual ~Cell();

  Cell(const Cell& from);

  inline Cell& operator=(const Cell& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Cell(Cell&& from) noexcept
    : Cell() {
    *this = ::std::move(from);
  }

  inline Cell& operator=(Cell&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Cell& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Cell* internal_default_instance() {
    return reinterpret_cast<const Cell*>(
               &_Cell_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Cell* other);
  friend void swap(Cell& a, Cell& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Cell* New() const final {
    return CreateMaybeMessage<Cell>(NULL);
  }

  Cell* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Cell>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Cell& from);
  void MergeFrom(const Cell& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Cell* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 seed = 1;
  void clear_seed();
  static const int kSeedFieldNumber = 1;
  ::google::protobuf::uint32 seed() const;
  void set_seed(::google::protobuf::uint32 value);

  // uint32 maxPin = 2;
  void clear_maxpin();
  static const int kMaxPinFieldNumber = 2;
  ::google::protobuf::uint32 maxpin() const;
  void set_maxpin(::google::protobuf::uint32 value);

  // double resolution = 4;
  void clear_resolution();
  static const int kResolutionFieldNumber = 4;
  double resolution() const;
  void set_resolution(double value);

  // uint32 startNet = 3;
  void clear_startnet();
  static const int kStartNetFieldNumber = 3;
  ::google::protobuf::uint32 startnet() const;
  void set_startnet(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.Cell)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 seed_;
  ::google::protobuf::uint32 maxpin_;
  double resolution_;
  ::google::protobuf::uint32 startnet_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AllConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Placement : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.Placement) */ {
 public:
  Placement();
  virtual ~Placement();

  Placement(const Placement& from);

  inline Placement& operator=(const Placement& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Placement(Placement&& from) noexcept
    : Placement() {
    *this = ::std::move(from);
  }

  inline Placement& operator=(Placement&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Placement& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Placement* internal_default_instance() {
    return reinterpret_cast<const Placement*>(
               &_Placement_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(Placement* other);
  friend void swap(Placement& a, Placement& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Placement* New() const final {
    return CreateMaybeMessage<Placement>(NULL);
  }

  Placement* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Placement>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Placement& from);
  void MergeFrom(const Placement& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Placement* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .proto.RoutingCost routing = 7;
  bool has_routing() const;
  void clear_routing();
  static const int kRoutingFieldNumber = 7;
  private:
  const ::proto::RoutingCost& _internal_routing() const;
  public:
  const ::proto::RoutingCost& routing() const;
  ::proto::RoutingCost* release_routing();
  ::proto::RoutingCost* mutable_routing();
  void set_allocated_routing(::proto::RoutingCost* routing);

  // .proto.Cell cell = 8;
  bool has_cell() const;
  void clear_cell();
  static const int kCellFieldNumber = 8;
  private:
  const ::proto::Cell& _internal_cell() const;
  public:
  const ::proto::Cell& cell() const;
  ::proto::Cell* release_cell();
  ::proto::Cell* mutable_cell();
  void set_allocated_cell(::proto::Cell* cell);

  // double initial_thickness = 1;
  void clear_initial_thickness();
  static const int kInitialThicknessFieldNumber = 1;
  double initial_thickness() const;
  void set_initial_thickness(double value);

  // double decrement_factor = 2;
  void clear_decrement_factor();
  static const int kDecrementFactorFieldNumber = 2;
  double decrement_factor() const;
  void set_decrement_factor(double value);

  // double minimal_thickness = 3;
  void clear_minimal_thickness();
  static const int kMinimalThicknessFieldNumber = 3;
  double minimal_thickness() const;
  void set_minimal_thickness(double value);

  // double smoothing_tension = 4;
  void clear_smoothing_tension();
  static const int kSmoothingTensionFieldNumber = 4;
  double smoothing_tension() const;
  void set_smoothing_tension(double value);

  // uint64 max_routing_attempt = 6;
  void clear_max_routing_attempt();
  static const int kMaxRoutingAttemptFieldNumber = 6;
  ::google::protobuf::uint64 max_routing_attempt() const;
  void set_max_routing_attempt(::google::protobuf::uint64 value);

  // uint32 smoothing_iteration = 5;
  void clear_smoothing_iteration();
  static const int kSmoothingIterationFieldNumber = 5;
  ::google::protobuf::uint32 smoothing_iteration() const;
  void set_smoothing_iteration(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.Placement)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::proto::RoutingCost* routing_;
  ::proto::Cell* cell_;
  double initial_thickness_;
  double decrement_factor_;
  double minimal_thickness_;
  double smoothing_tension_;
  ::google::protobuf::uint64 max_routing_attempt_;
  ::google::protobuf::uint32 smoothing_iteration_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AllConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AlternateRouting : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.AlternateRouting) */ {
 public:
  AlternateRouting();
  virtual ~AlternateRouting();

  AlternateRouting(const AlternateRouting& from);

  inline AlternateRouting& operator=(const AlternateRouting& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AlternateRouting(AlternateRouting&& from) noexcept
    : AlternateRouting() {
    *this = ::std::move(from);
  }

  inline AlternateRouting& operator=(AlternateRouting&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AlternateRouting& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AlternateRouting* internal_default_instance() {
    return reinterpret_cast<const AlternateRouting*>(
               &_AlternateRouting_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(AlternateRouting* other);
  friend void swap(AlternateRouting& a, AlternateRouting& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AlternateRouting* New() const final {
    return CreateMaybeMessage<AlternateRouting>(NULL);
  }

  AlternateRouting* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AlternateRouting>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AlternateRouting& from);
  void MergeFrom(const AlternateRouting& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AlternateRouting* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double maxThickness = 1;
  void clear_maxthickness();
  static const int kMaxThicknessFieldNumber = 1;
  double maxthickness() const;
  void set_maxthickness(double value);

  // double minThickness = 2;
  void clear_minthickness();
  static const int kMinThicknessFieldNumber = 2;
  double minthickness() const;
  void set_minthickness(double value);

  // double thicknessPercent = 4;
  void clear_thicknesspercent();
  static const int kThicknessPercentFieldNumber = 4;
  double thicknesspercent() const;
  void set_thicknesspercent(double value);

  // double simplifyDist = 5;
  void clear_simplifydist();
  static const int kSimplifyDistFieldNumber = 5;
  double simplifydist() const;
  void set_simplifydist(double value);

  // uint32 pruning = 3;
  void clear_pruning();
  static const int kPruningFieldNumber = 3;
  ::google::protobuf::uint32 pruning() const;
  void set_pruning(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.AlternateRouting)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double maxthickness_;
  double minthickness_;
  double thicknesspercent_;
  double simplifydist_;
  ::google::protobuf::uint32 pruning_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AllConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Routing : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.Routing) */ {
 public:
  Routing();
  virtual ~Routing();

  Routing(const Routing& from);

  inline Routing& operator=(const Routing& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Routing(Routing&& from) noexcept
    : Routing() {
    *this = ::std::move(from);
  }

  inline Routing& operator=(Routing&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Routing& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Routing* internal_default_instance() {
    return reinterpret_cast<const Routing*>(
               &_Routing_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(Routing* other);
  friend void swap(Routing& a, Routing& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Routing* New() const final {
    return CreateMaybeMessage<Routing>(NULL);
  }

  Routing* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Routing>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Routing& from);
  void MergeFrom(const Routing& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Routing* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .proto.Filepaths filepaths = 1;
  bool has_filepaths() const;
  void clear_filepaths();
  static const int kFilepathsFieldNumber = 1;
  private:
  const ::proto::Filepaths& _internal_filepaths() const;
  public:
  const ::proto::Filepaths& filepaths() const;
  ::proto::Filepaths* release_filepaths();
  ::proto::Filepaths* mutable_filepaths();
  void set_allocated_filepaths(::proto::Filepaths* filepaths);

  // .proto.Placement placement = 2;
  bool has_placement() const;
  void clear_placement();
  static const int kPlacementFieldNumber = 2;
  private:
  const ::proto::Placement& _internal_placement() const;
  public:
  const ::proto::Placement& placement() const;
  ::proto::Placement* release_placement();
  ::proto::Placement* mutable_placement();
  void set_allocated_placement(::proto::Placement* placement);

  // .proto.AlternateRouting alternateRouting = 3;
  bool has_alternaterouting() const;
  void clear_alternaterouting();
  static const int kAlternateRoutingFieldNumber = 3;
  private:
  const ::proto::AlternateRouting& _internal_alternaterouting() const;
  public:
  const ::proto::AlternateRouting& alternaterouting() const;
  ::proto::AlternateRouting* release_alternaterouting();
  ::proto::AlternateRouting* mutable_alternaterouting();
  void set_allocated_alternaterouting(::proto::AlternateRouting* alternaterouting);

  // @@protoc_insertion_point(class_scope:proto.Routing)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::proto::Filepaths* filepaths_;
  ::proto::Placement* placement_;
  ::proto::AlternateRouting* alternaterouting_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AllConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AllConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.AllConfig) */ {
 public:
  AllConfig();
  virtual ~AllConfig();

  AllConfig(const AllConfig& from);

  inline AllConfig& operator=(const AllConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AllConfig(AllConfig&& from) noexcept
    : AllConfig() {
    *this = ::std::move(from);
  }

  inline AllConfig& operator=(AllConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AllConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AllConfig* internal_default_instance() {
    return reinterpret_cast<const AllConfig*>(
               &_AllConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(AllConfig* other);
  friend void swap(AllConfig& a, AllConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AllConfig* New() const final {
    return CreateMaybeMessage<AllConfig>(NULL);
  }

  AllConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AllConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AllConfig& from);
  void MergeFrom(const AllConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AllConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .proto.Routing routing = 1;
  bool has_routing() const;
  void clear_routing();
  static const int kRoutingFieldNumber = 1;
  private:
  const ::proto::Routing& _internal_routing() const;
  public:
  const ::proto::Routing& routing() const;
  ::proto::Routing* release_routing();
  ::proto::Routing* mutable_routing();
  void set_allocated_routing(::proto::Routing* routing);

  // .proto.GraphicRendering gGraphicRendering = 2;
  bool has_ggraphicrendering() const;
  void clear_ggraphicrendering();
  static const int kGGraphicRenderingFieldNumber = 2;
  private:
  const ::proto::GraphicRendering& _internal_ggraphicrendering() const;
  public:
  const ::proto::GraphicRendering& ggraphicrendering() const;
  ::proto::GraphicRendering* release_ggraphicrendering();
  ::proto::GraphicRendering* mutable_ggraphicrendering();
  void set_allocated_ggraphicrendering(::proto::GraphicRendering* ggraphicrendering);

  // .proto.SkeletonGrid skeletonGrid = 3;
  bool has_skeletongrid() const;
  void clear_skeletongrid();
  static const int kSkeletonGridFieldNumber = 3;
  private:
  const ::proto::SkeletonGrid& _internal_skeletongrid() const;
  public:
  const ::proto::SkeletonGrid& skeletongrid() const;
  ::proto::SkeletonGrid* release_skeletongrid();
  ::proto::SkeletonGrid* mutable_skeletongrid();
  void set_allocated_skeletongrid(::proto::SkeletonGrid* skeletongrid);

  // @@protoc_insertion_point(class_scope:proto.AllConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::proto::Routing* routing_;
  ::proto::GraphicRendering* ggraphicrendering_;
  ::proto::SkeletonGrid* skeletongrid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AllConfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Filepaths

// string outputfile = 1;
inline void Filepaths::clear_outputfile() {
  outputfile_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Filepaths::outputfile() const {
  // @@protoc_insertion_point(field_get:proto.Filepaths.outputfile)
  return outputfile_.GetNoArena();
}
inline void Filepaths::set_outputfile(const ::std::string& value) {
  
  outputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.Filepaths.outputfile)
}
#if LANG_CXX11
inline void Filepaths::set_outputfile(::std::string&& value) {
  
  outputfile_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.Filepaths.outputfile)
}
#endif
inline void Filepaths::set_outputfile(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  outputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Filepaths.outputfile)
}
inline void Filepaths::set_outputfile(const char* value, size_t size) {
  
  outputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Filepaths.outputfile)
}
inline ::std::string* Filepaths::mutable_outputfile() {
  
  // @@protoc_insertion_point(field_mutable:proto.Filepaths.outputfile)
  return outputfile_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Filepaths::release_outputfile() {
  // @@protoc_insertion_point(field_release:proto.Filepaths.outputfile)
  
  return outputfile_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Filepaths::set_allocated_outputfile(::std::string* outputfile) {
  if (outputfile != NULL) {
    
  } else {
    
  }
  outputfile_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), outputfile);
  // @@protoc_insertion_point(field_set_allocated:proto.Filepaths.outputfile)
}

// string inputfile = 2;
inline void Filepaths::clear_inputfile() {
  inputfile_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Filepaths::inputfile() const {
  // @@protoc_insertion_point(field_get:proto.Filepaths.inputfile)
  return inputfile_.GetNoArena();
}
inline void Filepaths::set_inputfile(const ::std::string& value) {
  
  inputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.Filepaths.inputfile)
}
#if LANG_CXX11
inline void Filepaths::set_inputfile(::std::string&& value) {
  
  inputfile_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.Filepaths.inputfile)
}
#endif
inline void Filepaths::set_inputfile(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  inputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Filepaths.inputfile)
}
inline void Filepaths::set_inputfile(const char* value, size_t size) {
  
  inputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Filepaths.inputfile)
}
inline ::std::string* Filepaths::mutable_inputfile() {
  
  // @@protoc_insertion_point(field_mutable:proto.Filepaths.inputfile)
  return inputfile_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Filepaths::release_inputfile() {
  // @@protoc_insertion_point(field_release:proto.Filepaths.inputfile)
  
  return inputfile_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Filepaths::set_allocated_inputfile(::std::string* inputfile) {
  if (inputfile != NULL) {
    
  } else {
    
  }
  inputfile_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), inputfile);
  // @@protoc_insertion_point(field_set_allocated:proto.Filepaths.inputfile)
}

// -------------------------------------------------------------------

// PenStroke

// double thickness = 1;
inline void PenStroke::clear_thickness() {
  thickness_ = 0;
}
inline double PenStroke::thickness() const {
  // @@protoc_insertion_point(field_get:proto.PenStroke.thickness)
  return thickness_;
}
inline void PenStroke::set_thickness(double value) {
  
  thickness_ = value;
  // @@protoc_insertion_point(field_set:proto.PenStroke.thickness)
}

// double antisymmetric_amplitude = 2;
inline void PenStroke::clear_antisymmetric_amplitude() {
  antisymmetric_amplitude_ = 0;
}
inline double PenStroke::antisymmetric_amplitude() const {
  // @@protoc_insertion_point(field_get:proto.PenStroke.antisymmetric_amplitude)
  return antisymmetric_amplitude_;
}
inline void PenStroke::set_antisymmetric_amplitude(double value) {
  
  antisymmetric_amplitude_ = value;
  // @@protoc_insertion_point(field_set:proto.PenStroke.antisymmetric_amplitude)
}

// double antisymmetric_freq = 3;
inline void PenStroke::clear_antisymmetric_freq() {
  antisymmetric_freq_ = 0;
}
inline double PenStroke::antisymmetric_freq() const {
  // @@protoc_insertion_point(field_get:proto.PenStroke.antisymmetric_freq)
  return antisymmetric_freq_;
}
inline void PenStroke::set_antisymmetric_freq(double value) {
  
  antisymmetric_freq_ = value;
  // @@protoc_insertion_point(field_set:proto.PenStroke.antisymmetric_freq)
}

// double antisymmetric_seed = 4;
inline void PenStroke::clear_antisymmetric_seed() {
  antisymmetric_seed_ = 0;
}
inline double PenStroke::antisymmetric_seed() const {
  // @@protoc_insertion_point(field_get:proto.PenStroke.antisymmetric_seed)
  return antisymmetric_seed_;
}
inline void PenStroke::set_antisymmetric_seed(double value) {
  
  antisymmetric_seed_ = value;
  // @@protoc_insertion_point(field_set:proto.PenStroke.antisymmetric_seed)
}

// double symmetric_amplitude = 5;
inline void PenStroke::clear_symmetric_amplitude() {
  symmetric_amplitude_ = 0;
}
inline double PenStroke::symmetric_amplitude() const {
  // @@protoc_insertion_point(field_get:proto.PenStroke.symmetric_amplitude)
  return symmetric_amplitude_;
}
inline void PenStroke::set_symmetric_amplitude(double value) {
  
  symmetric_amplitude_ = value;
  // @@protoc_insertion_point(field_set:proto.PenStroke.symmetric_amplitude)
}

// double symmetric_freq = 6;
inline void PenStroke::clear_symmetric_freq() {
  symmetric_freq_ = 0;
}
inline double PenStroke::symmetric_freq() const {
  // @@protoc_insertion_point(field_get:proto.PenStroke.symmetric_freq)
  return symmetric_freq_;
}
inline void PenStroke::set_symmetric_freq(double value) {
  
  symmetric_freq_ = value;
  // @@protoc_insertion_point(field_set:proto.PenStroke.symmetric_freq)
}

// double symmetric_seed = 7;
inline void PenStroke::clear_symmetric_seed() {
  symmetric_seed_ = 0;
}
inline double PenStroke::symmetric_seed() const {
  // @@protoc_insertion_point(field_get:proto.PenStroke.symmetric_seed)
  return symmetric_seed_;
}
inline void PenStroke::set_symmetric_seed(double value) {
  
  symmetric_seed_ = value;
  // @@protoc_insertion_point(field_set:proto.PenStroke.symmetric_seed)
}

// double resolution = 8;
inline void PenStroke::clear_resolution() {
  resolution_ = 0;
}
inline double PenStroke::resolution() const {
  // @@protoc_insertion_point(field_get:proto.PenStroke.resolution)
  return resolution_;
}
inline void PenStroke::set_resolution(double value) {
  
  resolution_ = value;
  // @@protoc_insertion_point(field_set:proto.PenStroke.resolution)
}

// -------------------------------------------------------------------

// GraphicRendering

// string outputfile = 1;
inline void GraphicRendering::clear_outputfile() {
  outputfile_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GraphicRendering::outputfile() const {
  // @@protoc_insertion_point(field_get:proto.GraphicRendering.outputfile)
  return outputfile_.GetNoArena();
}
inline void GraphicRendering::set_outputfile(const ::std::string& value) {
  
  outputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.GraphicRendering.outputfile)
}
#if LANG_CXX11
inline void GraphicRendering::set_outputfile(::std::string&& value) {
  
  outputfile_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.GraphicRendering.outputfile)
}
#endif
inline void GraphicRendering::set_outputfile(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  outputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.GraphicRendering.outputfile)
}
inline void GraphicRendering::set_outputfile(const char* value, size_t size) {
  
  outputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.GraphicRendering.outputfile)
}
inline ::std::string* GraphicRendering::mutable_outputfile() {
  
  // @@protoc_insertion_point(field_mutable:proto.GraphicRendering.outputfile)
  return outputfile_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GraphicRendering::release_outputfile() {
  // @@protoc_insertion_point(field_release:proto.GraphicRendering.outputfile)
  
  return outputfile_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GraphicRendering::set_allocated_outputfile(::std::string* outputfile) {
  if (outputfile != NULL) {
    
  } else {
    
  }
  outputfile_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), outputfile);
  // @@protoc_insertion_point(field_set_allocated:proto.GraphicRendering.outputfile)
}

// string inputfile = 2;
inline void GraphicRendering::clear_inputfile() {
  inputfile_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GraphicRendering::inputfile() const {
  // @@protoc_insertion_point(field_get:proto.GraphicRendering.inputfile)
  return inputfile_.GetNoArena();
}
inline void GraphicRendering::set_inputfile(const ::std::string& value) {
  
  inputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.GraphicRendering.inputfile)
}
#if LANG_CXX11
inline void GraphicRendering::set_inputfile(::std::string&& value) {
  
  inputfile_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.GraphicRendering.inputfile)
}
#endif
inline void GraphicRendering::set_inputfile(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  inputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.GraphicRendering.inputfile)
}
inline void GraphicRendering::set_inputfile(const char* value, size_t size) {
  
  inputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.GraphicRendering.inputfile)
}
inline ::std::string* GraphicRendering::mutable_inputfile() {
  
  // @@protoc_insertion_point(field_mutable:proto.GraphicRendering.inputfile)
  return inputfile_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GraphicRendering::release_inputfile() {
  // @@protoc_insertion_point(field_release:proto.GraphicRendering.inputfile)
  
  return inputfile_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GraphicRendering::set_allocated_inputfile(::std::string* inputfile) {
  if (inputfile != NULL) {
    
  } else {
    
  }
  inputfile_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), inputfile);
  // @@protoc_insertion_point(field_set_allocated:proto.GraphicRendering.inputfile)
}

// double smoothing_tension = 3;
inline void GraphicRendering::clear_smoothing_tension() {
  smoothing_tension_ = 0;
}
inline double GraphicRendering::smoothing_tension() const {
  // @@protoc_insertion_point(field_get:proto.GraphicRendering.smoothing_tension)
  return smoothing_tension_;
}
inline void GraphicRendering::set_smoothing_tension(double value) {
  
  smoothing_tension_ = value;
  // @@protoc_insertion_point(field_set:proto.GraphicRendering.smoothing_tension)
}

// double smoothing_iterations = 4;
inline void GraphicRendering::clear_smoothing_iterations() {
  smoothing_iterations_ = 0;
}
inline double GraphicRendering::smoothing_iterations() const {
  // @@protoc_insertion_point(field_get:proto.GraphicRendering.smoothing_iterations)
  return smoothing_iterations_;
}
inline void GraphicRendering::set_smoothing_iterations(double value) {
  
  smoothing_iterations_ = value;
  // @@protoc_insertion_point(field_set:proto.GraphicRendering.smoothing_iterations)
}

// .proto.PenStroke penConfig = 9;
inline bool GraphicRendering::has_penconfig() const {
  return this != internal_default_instance() && penconfig_ != NULL;
}
inline void GraphicRendering::clear_penconfig() {
  if (GetArenaNoVirtual() == NULL && penconfig_ != NULL) {
    delete penconfig_;
  }
  penconfig_ = NULL;
}
inline const ::proto::PenStroke& GraphicRendering::_internal_penconfig() const {
  return *penconfig_;
}
inline const ::proto::PenStroke& GraphicRendering::penconfig() const {
  const ::proto::PenStroke* p = penconfig_;
  // @@protoc_insertion_point(field_get:proto.GraphicRendering.penConfig)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::PenStroke*>(
      &::proto::_PenStroke_default_instance_);
}
inline ::proto::PenStroke* GraphicRendering::release_penconfig() {
  // @@protoc_insertion_point(field_release:proto.GraphicRendering.penConfig)
  
  ::proto::PenStroke* temp = penconfig_;
  penconfig_ = NULL;
  return temp;
}
inline ::proto::PenStroke* GraphicRendering::mutable_penconfig() {
  
  if (penconfig_ == NULL) {
    auto* p = CreateMaybeMessage<::proto::PenStroke>(GetArenaNoVirtual());
    penconfig_ = p;
  }
  // @@protoc_insertion_point(field_mutable:proto.GraphicRendering.penConfig)
  return penconfig_;
}
inline void GraphicRendering::set_allocated_penconfig(::proto::PenStroke* penconfig) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete penconfig_;
  }
  if (penconfig) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      penconfig = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, penconfig, submessage_arena);
    }
    
  } else {
    
  }
  penconfig_ = penconfig;
  // @@protoc_insertion_point(field_set_allocated:proto.GraphicRendering.penConfig)
}

// -------------------------------------------------------------------

// SkeletonGrid

// string outputfile = 1;
inline void SkeletonGrid::clear_outputfile() {
  outputfile_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SkeletonGrid::outputfile() const {
  // @@protoc_insertion_point(field_get:proto.SkeletonGrid.outputfile)
  return outputfile_.GetNoArena();
}
inline void SkeletonGrid::set_outputfile(const ::std::string& value) {
  
  outputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.SkeletonGrid.outputfile)
}
#if LANG_CXX11
inline void SkeletonGrid::set_outputfile(::std::string&& value) {
  
  outputfile_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.SkeletonGrid.outputfile)
}
#endif
inline void SkeletonGrid::set_outputfile(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  outputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.SkeletonGrid.outputfile)
}
inline void SkeletonGrid::set_outputfile(const char* value, size_t size) {
  
  outputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.SkeletonGrid.outputfile)
}
inline ::std::string* SkeletonGrid::mutable_outputfile() {
  
  // @@protoc_insertion_point(field_mutable:proto.SkeletonGrid.outputfile)
  return outputfile_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SkeletonGrid::release_outputfile() {
  // @@protoc_insertion_point(field_release:proto.SkeletonGrid.outputfile)
  
  return outputfile_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SkeletonGrid::set_allocated_outputfile(::std::string* outputfile) {
  if (outputfile != NULL) {
    
  } else {
    
  }
  outputfile_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), outputfile);
  // @@protoc_insertion_point(field_set_allocated:proto.SkeletonGrid.outputfile)
}

// string inputfile = 2;
inline void SkeletonGrid::clear_inputfile() {
  inputfile_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SkeletonGrid::inputfile() const {
  // @@protoc_insertion_point(field_get:proto.SkeletonGrid.inputfile)
  return inputfile_.GetNoArena();
}
inline void SkeletonGrid::set_inputfile(const ::std::string& value) {
  
  inputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.SkeletonGrid.inputfile)
}
#if LANG_CXX11
inline void SkeletonGrid::set_inputfile(::std::string&& value) {
  
  inputfile_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.SkeletonGrid.inputfile)
}
#endif
inline void SkeletonGrid::set_inputfile(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  inputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.SkeletonGrid.inputfile)
}
inline void SkeletonGrid::set_inputfile(const char* value, size_t size) {
  
  inputfile_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.SkeletonGrid.inputfile)
}
inline ::std::string* SkeletonGrid::mutable_inputfile() {
  
  // @@protoc_insertion_point(field_mutable:proto.SkeletonGrid.inputfile)
  return inputfile_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SkeletonGrid::release_inputfile() {
  // @@protoc_insertion_point(field_release:proto.SkeletonGrid.inputfile)
  
  return inputfile_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SkeletonGrid::set_allocated_inputfile(::std::string* inputfile) {
  if (inputfile != NULL) {
    
  } else {
    
  }
  inputfile_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), inputfile);
  // @@protoc_insertion_point(field_set_allocated:proto.SkeletonGrid.inputfile)
}

// double simplificationOfOriginalSVG = 3;
inline void SkeletonGrid::clear_simplificationoforiginalsvg() {
  simplificationoforiginalsvg_ = 0;
}
inline double SkeletonGrid::simplificationoforiginalsvg() const {
  // @@protoc_insertion_point(field_get:proto.SkeletonGrid.simplificationOfOriginalSVG)
  return simplificationoforiginalsvg_;
}
inline void SkeletonGrid::set_simplificationoforiginalsvg(double value) {
  
  simplificationoforiginalsvg_ = value;
  // @@protoc_insertion_point(field_set:proto.SkeletonGrid.simplificationOfOriginalSVG)
}

// double max_sep = 4;
inline void SkeletonGrid::clear_max_sep() {
  max_sep_ = 0;
}
inline double SkeletonGrid::max_sep() const {
  // @@protoc_insertion_point(field_get:proto.SkeletonGrid.max_sep)
  return max_sep_;
}
inline void SkeletonGrid::set_max_sep(double value) {
  
  max_sep_ = value;
  // @@protoc_insertion_point(field_set:proto.SkeletonGrid.max_sep)
}

// double min_sep = 5;
inline void SkeletonGrid::clear_min_sep() {
  min_sep_ = 0;
}
inline double SkeletonGrid::min_sep() const {
  // @@protoc_insertion_point(field_get:proto.SkeletonGrid.min_sep)
  return min_sep_;
}
inline void SkeletonGrid::set_min_sep(double value) {
  
  min_sep_ = value;
  // @@protoc_insertion_point(field_set:proto.SkeletonGrid.min_sep)
}

// uint32 seed = 6;
inline void SkeletonGrid::clear_seed() {
  seed_ = 0u;
}
inline ::google::protobuf::uint32 SkeletonGrid::seed() const {
  // @@protoc_insertion_point(field_get:proto.SkeletonGrid.seed)
  return seed_;
}
inline void SkeletonGrid::set_seed(::google::protobuf::uint32 value) {
  
  seed_ = value;
  // @@protoc_insertion_point(field_set:proto.SkeletonGrid.seed)
}

// -------------------------------------------------------------------

// RoutingCost

// uint32 seed = 1;
inline void RoutingCost::clear_seed() {
  seed_ = 0u;
}
inline ::google::protobuf::uint32 RoutingCost::seed() const {
  // @@protoc_insertion_point(field_get:proto.RoutingCost.seed)
  return seed_;
}
inline void RoutingCost::set_seed(::google::protobuf::uint32 value) {
  
  seed_ = value;
  // @@protoc_insertion_point(field_set:proto.RoutingCost.seed)
}

// int32 max_random = 2;
inline void RoutingCost::clear_max_random() {
  max_random_ = 0;
}
inline ::google::protobuf::int32 RoutingCost::max_random() const {
  // @@protoc_insertion_point(field_get:proto.RoutingCost.max_random)
  return max_random_;
}
inline void RoutingCost::set_max_random(::google::protobuf::int32 value) {
  
  max_random_ = value;
  // @@protoc_insertion_point(field_set:proto.RoutingCost.max_random)
}

// int32 distance_unit_cost = 3;
inline void RoutingCost::clear_distance_unit_cost() {
  distance_unit_cost_ = 0;
}
inline ::google::protobuf::int32 RoutingCost::distance_unit_cost() const {
  // @@protoc_insertion_point(field_get:proto.RoutingCost.distance_unit_cost)
  return distance_unit_cost_;
}
inline void RoutingCost::set_distance_unit_cost(::google::protobuf::int32 value) {
  
  distance_unit_cost_ = value;
  // @@protoc_insertion_point(field_set:proto.RoutingCost.distance_unit_cost)
}

// int32 via_unit_cost = 4;
inline void RoutingCost::clear_via_unit_cost() {
  via_unit_cost_ = 0;
}
inline ::google::protobuf::int32 RoutingCost::via_unit_cost() const {
  // @@protoc_insertion_point(field_get:proto.RoutingCost.via_unit_cost)
  return via_unit_cost_;
}
inline void RoutingCost::set_via_unit_cost(::google::protobuf::int32 value) {
  
  via_unit_cost_ = value;
  // @@protoc_insertion_point(field_set:proto.RoutingCost.via_unit_cost)
}

// -------------------------------------------------------------------

// Cell

// uint32 seed = 1;
inline void Cell::clear_seed() {
  seed_ = 0u;
}
inline ::google::protobuf::uint32 Cell::seed() const {
  // @@protoc_insertion_point(field_get:proto.Cell.seed)
  return seed_;
}
inline void Cell::set_seed(::google::protobuf::uint32 value) {
  
  seed_ = value;
  // @@protoc_insertion_point(field_set:proto.Cell.seed)
}

// uint32 maxPin = 2;
inline void Cell::clear_maxpin() {
  maxpin_ = 0u;
}
inline ::google::protobuf::uint32 Cell::maxpin() const {
  // @@protoc_insertion_point(field_get:proto.Cell.maxPin)
  return maxpin_;
}
inline void Cell::set_maxpin(::google::protobuf::uint32 value) {
  
  maxpin_ = value;
  // @@protoc_insertion_point(field_set:proto.Cell.maxPin)
}

// uint32 startNet = 3;
inline void Cell::clear_startnet() {
  startnet_ = 0u;
}
inline ::google::protobuf::uint32 Cell::startnet() const {
  // @@protoc_insertion_point(field_get:proto.Cell.startNet)
  return startnet_;
}
inline void Cell::set_startnet(::google::protobuf::uint32 value) {
  
  startnet_ = value;
  // @@protoc_insertion_point(field_set:proto.Cell.startNet)
}

// double resolution = 4;
inline void Cell::clear_resolution() {
  resolution_ = 0;
}
inline double Cell::resolution() const {
  // @@protoc_insertion_point(field_get:proto.Cell.resolution)
  return resolution_;
}
inline void Cell::set_resolution(double value) {
  
  resolution_ = value;
  // @@protoc_insertion_point(field_set:proto.Cell.resolution)
}

// -------------------------------------------------------------------

// Placement

// double initial_thickness = 1;
inline void Placement::clear_initial_thickness() {
  initial_thickness_ = 0;
}
inline double Placement::initial_thickness() const {
  // @@protoc_insertion_point(field_get:proto.Placement.initial_thickness)
  return initial_thickness_;
}
inline void Placement::set_initial_thickness(double value) {
  
  initial_thickness_ = value;
  // @@protoc_insertion_point(field_set:proto.Placement.initial_thickness)
}

// double decrement_factor = 2;
inline void Placement::clear_decrement_factor() {
  decrement_factor_ = 0;
}
inline double Placement::decrement_factor() const {
  // @@protoc_insertion_point(field_get:proto.Placement.decrement_factor)
  return decrement_factor_;
}
inline void Placement::set_decrement_factor(double value) {
  
  decrement_factor_ = value;
  // @@protoc_insertion_point(field_set:proto.Placement.decrement_factor)
}

// double minimal_thickness = 3;
inline void Placement::clear_minimal_thickness() {
  minimal_thickness_ = 0;
}
inline double Placement::minimal_thickness() const {
  // @@protoc_insertion_point(field_get:proto.Placement.minimal_thickness)
  return minimal_thickness_;
}
inline void Placement::set_minimal_thickness(double value) {
  
  minimal_thickness_ = value;
  // @@protoc_insertion_point(field_set:proto.Placement.minimal_thickness)
}

// double smoothing_tension = 4;
inline void Placement::clear_smoothing_tension() {
  smoothing_tension_ = 0;
}
inline double Placement::smoothing_tension() const {
  // @@protoc_insertion_point(field_get:proto.Placement.smoothing_tension)
  return smoothing_tension_;
}
inline void Placement::set_smoothing_tension(double value) {
  
  smoothing_tension_ = value;
  // @@protoc_insertion_point(field_set:proto.Placement.smoothing_tension)
}

// uint32 smoothing_iteration = 5;
inline void Placement::clear_smoothing_iteration() {
  smoothing_iteration_ = 0u;
}
inline ::google::protobuf::uint32 Placement::smoothing_iteration() const {
  // @@protoc_insertion_point(field_get:proto.Placement.smoothing_iteration)
  return smoothing_iteration_;
}
inline void Placement::set_smoothing_iteration(::google::protobuf::uint32 value) {
  
  smoothing_iteration_ = value;
  // @@protoc_insertion_point(field_set:proto.Placement.smoothing_iteration)
}

// uint64 max_routing_attempt = 6;
inline void Placement::clear_max_routing_attempt() {
  max_routing_attempt_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Placement::max_routing_attempt() const {
  // @@protoc_insertion_point(field_get:proto.Placement.max_routing_attempt)
  return max_routing_attempt_;
}
inline void Placement::set_max_routing_attempt(::google::protobuf::uint64 value) {
  
  max_routing_attempt_ = value;
  // @@protoc_insertion_point(field_set:proto.Placement.max_routing_attempt)
}

// .proto.RoutingCost routing = 7;
inline bool Placement::has_routing() const {
  return this != internal_default_instance() && routing_ != NULL;
}
inline void Placement::clear_routing() {
  if (GetArenaNoVirtual() == NULL && routing_ != NULL) {
    delete routing_;
  }
  routing_ = NULL;
}
inline const ::proto::RoutingCost& Placement::_internal_routing() const {
  return *routing_;
}
inline const ::proto::RoutingCost& Placement::routing() const {
  const ::proto::RoutingCost* p = routing_;
  // @@protoc_insertion_point(field_get:proto.Placement.routing)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::RoutingCost*>(
      &::proto::_RoutingCost_default_instance_);
}
inline ::proto::RoutingCost* Placement::release_routing() {
  // @@protoc_insertion_point(field_release:proto.Placement.routing)
  
  ::proto::RoutingCost* temp = routing_;
  routing_ = NULL;
  return temp;
}
inline ::proto::RoutingCost* Placement::mutable_routing() {
  
  if (routing_ == NULL) {
    auto* p = CreateMaybeMessage<::proto::RoutingCost>(GetArenaNoVirtual());
    routing_ = p;
  }
  // @@protoc_insertion_point(field_mutable:proto.Placement.routing)
  return routing_;
}
inline void Placement::set_allocated_routing(::proto::RoutingCost* routing) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete routing_;
  }
  if (routing) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      routing = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, routing, submessage_arena);
    }
    
  } else {
    
  }
  routing_ = routing;
  // @@protoc_insertion_point(field_set_allocated:proto.Placement.routing)
}

// .proto.Cell cell = 8;
inline bool Placement::has_cell() const {
  return this != internal_default_instance() && cell_ != NULL;
}
inline void Placement::clear_cell() {
  if (GetArenaNoVirtual() == NULL && cell_ != NULL) {
    delete cell_;
  }
  cell_ = NULL;
}
inline const ::proto::Cell& Placement::_internal_cell() const {
  return *cell_;
}
inline const ::proto::Cell& Placement::cell() const {
  const ::proto::Cell* p = cell_;
  // @@protoc_insertion_point(field_get:proto.Placement.cell)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::Cell*>(
      &::proto::_Cell_default_instance_);
}
inline ::proto::Cell* Placement::release_cell() {
  // @@protoc_insertion_point(field_release:proto.Placement.cell)
  
  ::proto::Cell* temp = cell_;
  cell_ = NULL;
  return temp;
}
inline ::proto::Cell* Placement::mutable_cell() {
  
  if (cell_ == NULL) {
    auto* p = CreateMaybeMessage<::proto::Cell>(GetArenaNoVirtual());
    cell_ = p;
  }
  // @@protoc_insertion_point(field_mutable:proto.Placement.cell)
  return cell_;
}
inline void Placement::set_allocated_cell(::proto::Cell* cell) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete cell_;
  }
  if (cell) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      cell = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, cell, submessage_arena);
    }
    
  } else {
    
  }
  cell_ = cell;
  // @@protoc_insertion_point(field_set_allocated:proto.Placement.cell)
}

// -------------------------------------------------------------------

// AlternateRouting

// double maxThickness = 1;
inline void AlternateRouting::clear_maxthickness() {
  maxthickness_ = 0;
}
inline double AlternateRouting::maxthickness() const {
  // @@protoc_insertion_point(field_get:proto.AlternateRouting.maxThickness)
  return maxthickness_;
}
inline void AlternateRouting::set_maxthickness(double value) {
  
  maxthickness_ = value;
  // @@protoc_insertion_point(field_set:proto.AlternateRouting.maxThickness)
}

// double minThickness = 2;
inline void AlternateRouting::clear_minthickness() {
  minthickness_ = 0;
}
inline double AlternateRouting::minthickness() const {
  // @@protoc_insertion_point(field_get:proto.AlternateRouting.minThickness)
  return minthickness_;
}
inline void AlternateRouting::set_minthickness(double value) {
  
  minthickness_ = value;
  // @@protoc_insertion_point(field_set:proto.AlternateRouting.minThickness)
}

// uint32 pruning = 3;
inline void AlternateRouting::clear_pruning() {
  pruning_ = 0u;
}
inline ::google::protobuf::uint32 AlternateRouting::pruning() const {
  // @@protoc_insertion_point(field_get:proto.AlternateRouting.pruning)
  return pruning_;
}
inline void AlternateRouting::set_pruning(::google::protobuf::uint32 value) {
  
  pruning_ = value;
  // @@protoc_insertion_point(field_set:proto.AlternateRouting.pruning)
}

// double thicknessPercent = 4;
inline void AlternateRouting::clear_thicknesspercent() {
  thicknesspercent_ = 0;
}
inline double AlternateRouting::thicknesspercent() const {
  // @@protoc_insertion_point(field_get:proto.AlternateRouting.thicknessPercent)
  return thicknesspercent_;
}
inline void AlternateRouting::set_thicknesspercent(double value) {
  
  thicknesspercent_ = value;
  // @@protoc_insertion_point(field_set:proto.AlternateRouting.thicknessPercent)
}

// double simplifyDist = 5;
inline void AlternateRouting::clear_simplifydist() {
  simplifydist_ = 0;
}
inline double AlternateRouting::simplifydist() const {
  // @@protoc_insertion_point(field_get:proto.AlternateRouting.simplifyDist)
  return simplifydist_;
}
inline void AlternateRouting::set_simplifydist(double value) {
  
  simplifydist_ = value;
  // @@protoc_insertion_point(field_set:proto.AlternateRouting.simplifyDist)
}

// -------------------------------------------------------------------

// Routing

// .proto.Filepaths filepaths = 1;
inline bool Routing::has_filepaths() const {
  return this != internal_default_instance() && filepaths_ != NULL;
}
inline void Routing::clear_filepaths() {
  if (GetArenaNoVirtual() == NULL && filepaths_ != NULL) {
    delete filepaths_;
  }
  filepaths_ = NULL;
}
inline const ::proto::Filepaths& Routing::_internal_filepaths() const {
  return *filepaths_;
}
inline const ::proto::Filepaths& Routing::filepaths() const {
  const ::proto::Filepaths* p = filepaths_;
  // @@protoc_insertion_point(field_get:proto.Routing.filepaths)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::Filepaths*>(
      &::proto::_Filepaths_default_instance_);
}
inline ::proto::Filepaths* Routing::release_filepaths() {
  // @@protoc_insertion_point(field_release:proto.Routing.filepaths)
  
  ::proto::Filepaths* temp = filepaths_;
  filepaths_ = NULL;
  return temp;
}
inline ::proto::Filepaths* Routing::mutable_filepaths() {
  
  if (filepaths_ == NULL) {
    auto* p = CreateMaybeMessage<::proto::Filepaths>(GetArenaNoVirtual());
    filepaths_ = p;
  }
  // @@protoc_insertion_point(field_mutable:proto.Routing.filepaths)
  return filepaths_;
}
inline void Routing::set_allocated_filepaths(::proto::Filepaths* filepaths) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete filepaths_;
  }
  if (filepaths) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      filepaths = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, filepaths, submessage_arena);
    }
    
  } else {
    
  }
  filepaths_ = filepaths;
  // @@protoc_insertion_point(field_set_allocated:proto.Routing.filepaths)
}

// .proto.Placement placement = 2;
inline bool Routing::has_placement() const {
  return this != internal_default_instance() && placement_ != NULL;
}
inline void Routing::clear_placement() {
  if (GetArenaNoVirtual() == NULL && placement_ != NULL) {
    delete placement_;
  }
  placement_ = NULL;
}
inline const ::proto::Placement& Routing::_internal_placement() const {
  return *placement_;
}
inline const ::proto::Placement& Routing::placement() const {
  const ::proto::Placement* p = placement_;
  // @@protoc_insertion_point(field_get:proto.Routing.placement)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::Placement*>(
      &::proto::_Placement_default_instance_);
}
inline ::proto::Placement* Routing::release_placement() {
  // @@protoc_insertion_point(field_release:proto.Routing.placement)
  
  ::proto::Placement* temp = placement_;
  placement_ = NULL;
  return temp;
}
inline ::proto::Placement* Routing::mutable_placement() {
  
  if (placement_ == NULL) {
    auto* p = CreateMaybeMessage<::proto::Placement>(GetArenaNoVirtual());
    placement_ = p;
  }
  // @@protoc_insertion_point(field_mutable:proto.Routing.placement)
  return placement_;
}
inline void Routing::set_allocated_placement(::proto::Placement* placement) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete placement_;
  }
  if (placement) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      placement = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, placement, submessage_arena);
    }
    
  } else {
    
  }
  placement_ = placement;
  // @@protoc_insertion_point(field_set_allocated:proto.Routing.placement)
}

// .proto.AlternateRouting alternateRouting = 3;
inline bool Routing::has_alternaterouting() const {
  return this != internal_default_instance() && alternaterouting_ != NULL;
}
inline void Routing::clear_alternaterouting() {
  if (GetArenaNoVirtual() == NULL && alternaterouting_ != NULL) {
    delete alternaterouting_;
  }
  alternaterouting_ = NULL;
}
inline const ::proto::AlternateRouting& Routing::_internal_alternaterouting() const {
  return *alternaterouting_;
}
inline const ::proto::AlternateRouting& Routing::alternaterouting() const {
  const ::proto::AlternateRouting* p = alternaterouting_;
  // @@protoc_insertion_point(field_get:proto.Routing.alternateRouting)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::AlternateRouting*>(
      &::proto::_AlternateRouting_default_instance_);
}
inline ::proto::AlternateRouting* Routing::release_alternaterouting() {
  // @@protoc_insertion_point(field_release:proto.Routing.alternateRouting)
  
  ::proto::AlternateRouting* temp = alternaterouting_;
  alternaterouting_ = NULL;
  return temp;
}
inline ::proto::AlternateRouting* Routing::mutable_alternaterouting() {
  
  if (alternaterouting_ == NULL) {
    auto* p = CreateMaybeMessage<::proto::AlternateRouting>(GetArenaNoVirtual());
    alternaterouting_ = p;
  }
  // @@protoc_insertion_point(field_mutable:proto.Routing.alternateRouting)
  return alternaterouting_;
}
inline void Routing::set_allocated_alternaterouting(::proto::AlternateRouting* alternaterouting) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete alternaterouting_;
  }
  if (alternaterouting) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      alternaterouting = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, alternaterouting, submessage_arena);
    }
    
  } else {
    
  }
  alternaterouting_ = alternaterouting;
  // @@protoc_insertion_point(field_set_allocated:proto.Routing.alternateRouting)
}

// -------------------------------------------------------------------

// AllConfig

// .proto.Routing routing = 1;
inline bool AllConfig::has_routing() const {
  return this != internal_default_instance() && routing_ != NULL;
}
inline void AllConfig::clear_routing() {
  if (GetArenaNoVirtual() == NULL && routing_ != NULL) {
    delete routing_;
  }
  routing_ = NULL;
}
inline const ::proto::Routing& AllConfig::_internal_routing() const {
  return *routing_;
}
inline const ::proto::Routing& AllConfig::routing() const {
  const ::proto::Routing* p = routing_;
  // @@protoc_insertion_point(field_get:proto.AllConfig.routing)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::Routing*>(
      &::proto::_Routing_default_instance_);
}
inline ::proto::Routing* AllConfig::release_routing() {
  // @@protoc_insertion_point(field_release:proto.AllConfig.routing)
  
  ::proto::Routing* temp = routing_;
  routing_ = NULL;
  return temp;
}
inline ::proto::Routing* AllConfig::mutable_routing() {
  
  if (routing_ == NULL) {
    auto* p = CreateMaybeMessage<::proto::Routing>(GetArenaNoVirtual());
    routing_ = p;
  }
  // @@protoc_insertion_point(field_mutable:proto.AllConfig.routing)
  return routing_;
}
inline void AllConfig::set_allocated_routing(::proto::Routing* routing) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete routing_;
  }
  if (routing) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      routing = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, routing, submessage_arena);
    }
    
  } else {
    
  }
  routing_ = routing;
  // @@protoc_insertion_point(field_set_allocated:proto.AllConfig.routing)
}

// .proto.GraphicRendering gGraphicRendering = 2;
inline bool AllConfig::has_ggraphicrendering() const {
  return this != internal_default_instance() && ggraphicrendering_ != NULL;
}
inline void AllConfig::clear_ggraphicrendering() {
  if (GetArenaNoVirtual() == NULL && ggraphicrendering_ != NULL) {
    delete ggraphicrendering_;
  }
  ggraphicrendering_ = NULL;
}
inline const ::proto::GraphicRendering& AllConfig::_internal_ggraphicrendering() const {
  return *ggraphicrendering_;
}
inline const ::proto::GraphicRendering& AllConfig::ggraphicrendering() const {
  const ::proto::GraphicRendering* p = ggraphicrendering_;
  // @@protoc_insertion_point(field_get:proto.AllConfig.gGraphicRendering)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::GraphicRendering*>(
      &::proto::_GraphicRendering_default_instance_);
}
inline ::proto::GraphicRendering* AllConfig::release_ggraphicrendering() {
  // @@protoc_insertion_point(field_release:proto.AllConfig.gGraphicRendering)
  
  ::proto::GraphicRendering* temp = ggraphicrendering_;
  ggraphicrendering_ = NULL;
  return temp;
}
inline ::proto::GraphicRendering* AllConfig::mutable_ggraphicrendering() {
  
  if (ggraphicrendering_ == NULL) {
    auto* p = CreateMaybeMessage<::proto::GraphicRendering>(GetArenaNoVirtual());
    ggraphicrendering_ = p;
  }
  // @@protoc_insertion_point(field_mutable:proto.AllConfig.gGraphicRendering)
  return ggraphicrendering_;
}
inline void AllConfig::set_allocated_ggraphicrendering(::proto::GraphicRendering* ggraphicrendering) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete ggraphicrendering_;
  }
  if (ggraphicrendering) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      ggraphicrendering = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, ggraphicrendering, submessage_arena);
    }
    
  } else {
    
  }
  ggraphicrendering_ = ggraphicrendering;
  // @@protoc_insertion_point(field_set_allocated:proto.AllConfig.gGraphicRendering)
}

// .proto.SkeletonGrid skeletonGrid = 3;
inline bool AllConfig::has_skeletongrid() const {
  return this != internal_default_instance() && skeletongrid_ != NULL;
}
inline void AllConfig::clear_skeletongrid() {
  if (GetArenaNoVirtual() == NULL && skeletongrid_ != NULL) {
    delete skeletongrid_;
  }
  skeletongrid_ = NULL;
}
inline const ::proto::SkeletonGrid& AllConfig::_internal_skeletongrid() const {
  return *skeletongrid_;
}
inline const ::proto::SkeletonGrid& AllConfig::skeletongrid() const {
  const ::proto::SkeletonGrid* p = skeletongrid_;
  // @@protoc_insertion_point(field_get:proto.AllConfig.skeletonGrid)
  return p != NULL ? *p : *reinterpret_cast<const ::proto::SkeletonGrid*>(
      &::proto::_SkeletonGrid_default_instance_);
}
inline ::proto::SkeletonGrid* AllConfig::release_skeletongrid() {
  // @@protoc_insertion_point(field_release:proto.AllConfig.skeletonGrid)
  
  ::proto::SkeletonGrid* temp = skeletongrid_;
  skeletongrid_ = NULL;
  return temp;
}
inline ::proto::SkeletonGrid* AllConfig::mutable_skeletongrid() {
  
  if (skeletongrid_ == NULL) {
    auto* p = CreateMaybeMessage<::proto::SkeletonGrid>(GetArenaNoVirtual());
    skeletongrid_ = p;
  }
  // @@protoc_insertion_point(field_mutable:proto.AllConfig.skeletonGrid)
  return skeletongrid_;
}
inline void AllConfig::set_allocated_skeletongrid(::proto::SkeletonGrid* skeletongrid) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete skeletongrid_;
  }
  if (skeletongrid) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      skeletongrid = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, skeletongrid, submessage_arena);
    }
    
  } else {
    
  }
  skeletongrid_ = skeletongrid;
  // @@protoc_insertion_point(field_set_allocated:proto.AllConfig.skeletonGrid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_AllConfig_2eproto
